// <auto-generated />
using System;
using Data_Access_Layer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data_Access_Layer.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220327091106_InitalCreate")]
    partial class InitalCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data_Access_Layer.Models.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkillsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7be369da-0d1b-4544-b3cb-402828b5c95c"),
                            ContactNumber = "1",
                            DateOfBirth = new DateTime(2022, 3, 27, 9, 11, 5, 668, DateTimeKind.Utc).AddTicks(6761),
                            Email = "email",
                            FullName = "John Johnson",
                            SkillsId = 1
                        },
                        new
                        {
                            Id = new Guid("c793af7f-2a3c-4cd6-bff8-48805f7b8b06"),
                            ContactNumber = "2",
                            DateOfBirth = new DateTime(2022, 3, 27, 9, 11, 5, 668, DateTimeKind.Utc).AddTicks(8000),
                            Email = "email2",
                            FullName = "Jack Jackson",
                            SkillsId = 2
                        },
                        new
                        {
                            Id = new Guid("f5aa3442-b05e-4dda-8e02-56a1ff778e76"),
                            ContactNumber = "3",
                            DateOfBirth = new DateTime(2022, 3, 27, 9, 11, 5, 668, DateTimeKind.Utc).AddTicks(8023),
                            Email = "email3",
                            FullName = "Johnny Joe",
                            SkillsId = 3
                        });
                });

            modelBuilder.Entity("Data_Access_Layer.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Skill A"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Skill B"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Skill C"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
