// <auto-generated />
using System;
using Data_Access_Layer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data_Access_Layer.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data_Access_Layer.Entities.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e9006a52-ed6c-42f2-96c9-b7b61ab37fa6"),
                            ContactNumber = "1",
                            DateOfBirth = new DateTime(2022, 3, 31, 18, 41, 26, 177, DateTimeKind.Utc).AddTicks(6246),
                            Email = "email",
                            FullName = "John Johnson"
                        },
                        new
                        {
                            Id = new Guid("f2ba6cda-1b3e-44f2-80f8-9862e3dfb199"),
                            ContactNumber = "2",
                            DateOfBirth = new DateTime(2022, 3, 31, 18, 41, 26, 177, DateTimeKind.Utc).AddTicks(7148),
                            Email = "email2",
                            FullName = "Jack Jackson"
                        },
                        new
                        {
                            Id = new Guid("d0b2fecb-99c0-4d27-84c6-c53a40d08b20"),
                            ContactNumber = "3",
                            DateOfBirth = new DateTime(2022, 3, 31, 18, 41, 26, 177, DateTimeKind.Utc).AddTicks(7169),
                            Email = "email3",
                            FullName = "Johnny Joe"
                        });
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.CandidateAndSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("CandidatesAndSkills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b56b0a9e-062c-4ea5-840b-54cb05a076eb"),
                            CandidateId = new Guid("e9006a52-ed6c-42f2-96c9-b7b61ab37fa6"),
                            SkillId = new Guid("466b382c-c0f7-4cdc-a4bd-ea911e6afcc4")
                        });
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("466b382c-c0f7-4cdc-a4bd-ea911e6afcc4"),
                            Name = "Skill A"
                        },
                        new
                        {
                            Id = new Guid("bc28d359-2af6-4b3c-bab2-1bb9fa74cb75"),
                            Name = "Skill B"
                        },
                        new
                        {
                            Id = new Guid("1de38ee1-0f6d-4d59-8065-f1cb04161a87"),
                            Name = "Skill C"
                        });
                });

#pragma warning restore 612, 618
        }
    }
}
