// <auto-generated />
using System;
using Data_Access_Layer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data_Access_Layer.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data_Access_Layer.Entities.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a14b93c-398d-49b1-9930-e4fa640ab03e"),
                            ContactNumber = "1",
                            DateOfBirth = new DateTime(2022, 3, 28, 12, 20, 0, 679, DateTimeKind.Utc).AddTicks(7068),
                            Email = "email",
                            FullName = "John Johnson"
                        },
                        new
                        {
                            Id = new Guid("1a744aea-36b8-4504-84d9-fd8420f0fb4e"),
                            ContactNumber = "2",
                            DateOfBirth = new DateTime(2022, 3, 28, 12, 20, 0, 679, DateTimeKind.Utc).AddTicks(7696),
                            Email = "email2",
                            FullName = "Jack Jackson"
                        },
                        new
                        {
                            Id = new Guid("16fdfc19-52ad-48ec-b175-b4ea66cc2a5e"),
                            ContactNumber = "3",
                            DateOfBirth = new DateTime(2022, 3, 28, 12, 20, 0, 679, DateTimeKind.Utc).AddTicks(7717),
                            Email = "email3",
                            FullName = "Johnny Joe"
                        });
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01e9345f-461c-4e3d-b467-788436e149b7"),
                            Name = "Skill A"
                        },
                        new
                        {
                            Id = new Guid("9b79cd08-7333-44d4-a7bb-0d0fcfe2e30e"),
                            Name = "Skill B"
                        },
                        new
                        {
                            Id = new Guid("a306ad86-110b-46ed-8b48-91b37b1339b7"),
                            Name = "Skill C"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
